const cardDataList = [
    {
      image: "https://via.placeholder.com/150",
      title: "A Stylish Apt, 5 min walk to Queen Victoria Market",
      description: "Entire apartment rental in Collingwood",
      rating: 4.9,
      reviews: 202,
      location: "Collingwood VIC",
      features: ['1 bed', 'Wi-Fi'],
      price: 540,
      rareFind: true,
    },
    {
      image: "https://via.placeholder.com/150",
      title: "Modern Studio near Central Park",
      description: "Cozy studio in the heart of the city",
      rating: 4.7,
      reviews: 150,
      location: "New York, NY",
      features: ['Studio', 'Free Wi-Fi'],
      price: 320,
      rareFind: false,
    },
    {
      image: "https://via.placeholder.com/150",
      title: "Beachside Bungalow with Ocean View",
      description: "Relax by the beach with stunning views",
      rating: 4.8,
      reviews: 180,
      location: "Santa Monica, CA",
      features: ['2 beds', 'Kitchen'],
      price: 720,
      rareFind: true,
    },
    {
      image: "https://via.placeholder.com/150",
      title: "Luxury Apartment in Downtown",
      description: "High-rise apartment with skyline views",
      rating: 4.9,
      reviews: 220,
      location: "Sydney, AUS",
      features: ['2 beds', 'Pool'],
      price: 880,
      rareFind: false,
    },
    {
      image: "https://via.placeholder.com/150",
      title: "Charming Cottage in the Countryside",
      description: "Perfect getaway surrounded by nature",
      rating: 4.6,
      reviews: 95,
      location: "Blue Mountains, AUS",
      features: ['3 beds', 'Fireplace'],
      price: 450,
      rareFind: true,
    },
    {
      image: "https://via.placeholder.com/150",
      title: "Modern Loft with Rooftop Access",
      description: "Stylish loft with access to rooftop garden",
      rating: 4.8,
      reviews: 175,
      location: "San Francisco, CA",
      features: ['1 bed', 'Gym'],
      price: 650,
      rareFind: false,
    },
    {
      image: "https://via.placeholder.com/150",
      title: "Cozy Cabin near Hiking Trails",
      description: "Perfect for outdoor enthusiasts",
      rating: 4.7,
      reviews: 130,
      location: "Aspen, CO",
      features: ['1 bed', 'Hot Tub'],
      price: 500,
      rareFind: true,
    },
  ];

  export default cardDataList;