const cardDataList = [
  {
    image: require('../assests/images/card-1.jpg'),
    title: "A Stylish Apt, 5 min walk to Queen Victoria Market",
    description: "Entire apartment rental in Collingwood",
    rating: 4.9,
    reviews: 202,
    location: "Melbourne, US",
    features: ['1 bed', 'Wi-Fi'],
    price: 540,
    rareFind: true,
    startDate: '2024-08-01',
    endDate: '2024-12-31',
  },
  {
    image: require('../assests/images/card-2.png'),
    title: "Modern Studio near Central Park",
    description: "Cozy studio in the heart of the city",
    rating: 4.7,
    reviews: 150,
    location: "Suryapet, TS",
    features: ['Studio', 'Free Wi-Fi'],
    price: 320,
    rareFind: false,
    startDate: '2024-01-01',
    endDate: '2024-12-31',
  },
  {
    image: require('../assests/images/card-3.png'),
    title: "Beachside Bungalow with Ocean View",
    description: "Relax by the beach with stunning views",
    rating: 4.8,
    reviews: 180,
    location: "Melbourne, US",
    features: ['2 beds', 'Kitchen'],
    price: 720,
    rareFind: true,
    startDate: '2024-11-01',
    endDate: '2024-12-31',
  },
  {
    image: require('../assests/images/card-2.png'),
    title: "Luxury Apartment in Downtown",
    description: "High-rise apartment with skyline views",
    rating: 4.9,
    reviews: 220,
    location: "Sydney, AU",
    features: ['2 beds', 'Pool'],
    price: 880,
    rareFind: false,
    startDate: '2024-10-01',
    endDate: '2024-12-31',
  },
  {
    image: require('../assests/images/card-4.png'),
    title: "Charming Cottage in the Countryside",
    description: "Perfect getaway surrounded by nature",
    rating: 4.6,
    reviews: 95,
    location: "Sydney, AU",
    features: ['3 beds', 'Fireplace'],
    price: 450,
    rareFind: true,
    startDate: '2024-09-01',
    endDate: '2024-10-29',
  },
  {
    image: require('../assests/images/card-3.png'),
    title: "Modern Loft with Rooftop Access",
    description: "Stylish loft with access to rooftop garden",
    rating: 4.8,
    reviews: 175,
    location: "Hyderabad, TS",
    features: ['1 bed', 'Gym'],
    price: 650,
    rareFind: false,
    startDate: '2024-07-01',
    endDate: '2024-07-15',
  },
  {
    image: require('../assests/images/card-1.jpg'),
    title: "Cozy Cabin near Hiking Trails",
    description: "Perfect for outdoor enthusiasts",
    rating: 4.7,
    reviews: 130,
    location: "Sydney, AU",
    features: ['1 bed', 'Hot Tub'],
    price: 500,
    rareFind: true,
    startDate: '2024-01-01',
    endDate: '2024-12-31',
  },
];

export default cardDataList;
